// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldizjhrfnxaacedmbujt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaXpqaHJmbnhhYWNlZG1idWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjk5NTAsImV4cCI6MjA2Mzc0NTk1MH0.JQZBTYkrGLMLd_0HK6aPwZPpDkHEj023hps7Nggu2js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});