export const CANON = 'https://www.deeper.global';

export const TERM_LINKS: Record<string, string> = {
  // Inline glossary-style anchors → cornerstone/answer pages
  "panic attack": "/answers/anxiety/how-to-stop-a-panic-attack",
  "grounding": "/answers/anxiety/what-is-grounding-and-how-to-use-it",
  "burnout": "/answers/work-life/burnout-signs-and-recovery",
  "perfectionism": "/answers/identity/perfectionism-how-to-let-go",
  "people-pleasing": "/answers/work-life/stop-people-pleasing-at-work",
  "emotional numbness": "/answers/depression/emotional-numbness",
  "social anxiety": "/answers/relationships/supporting-social-anxiety",
  "overthinking": "/answers/anxiety/overthinking-before-bed",
  "anxiety": "/answers/anxiety/what-is-anxiety",
  "depression": "/answers/depression/what-is-depression",
  "stress": "/answers/anxiety/managing-stress",
  "therapy": "/answers/therapy/finding-the-right-therapist",
  "meditation": "/answers/mindfulness/meditation-for-beginners",
  "mindfulness": "/answers/mindfulness/what-is-mindfulness",
  "self-care": "/answers/self-care/self-care-practices",
  "boundaries": "/answers/relationships/setting-healthy-boundaries",
  "communication": "/answers/relationships/improving-communication",
  "grief": "/answers/grief/coping-with-loss",
  "trauma": "/answers/trauma/understanding-trauma",
  "self-worth": "/answers/identity/building-self-worth",
  "confidence": "/answers/identity/building-confidence",
  "relationships": "/answers/relationships/healthy-relationships",
  "parenting": "/answers/parenting/parenting-stress",
  "work-life balance": "/answers/work-life/achieving-work-life-balance",
  "sleep": "/answers/sleep/improving-sleep-quality",
  "anger": "/answers/emotions/managing-anger",
  "fear": "/answers/anxiety/understanding-fear",
  "loneliness": "/answers/relationships/coping-with-loneliness",
  "guilt": "/answers/emotions/dealing-with-guilt",
  "shame": "/answers/emotions/overcoming-shame",
  "forgiveness": "/answers/relationships/practicing-forgiveness",
  "gratitude": "/answers/mindfulness/practicing-gratitude",
  "resilience": "/answers/identity/building-resilience",
  "change": "/answers/life-transitions/coping-with-change",
  "identity": "/answers/identity/finding-your-identity",
  "purpose": "/answers/life-transitions/finding-purpose",
  "meaning": "/answers/spirituality/finding-meaning",
  "faith": "/answers/spirituality/faith-and-mental-health",
  "addiction": "/answers/addiction/understanding-addiction",
  "recovery": "/answers/addiction/recovery-journey",
  "healing": "/answers/healing/healing-process",
  "growth": "/answers/personal-growth/personal-growth",
  "transformation": "/answers/personal-growth/personal-transformation"
};

export const CATEGORY_ROUTES: Record<string,string> = {
  "Anxiety & Stress": "/answers/anxiety",
  "Depression": "/answers/depression",
  "Grief & Loss": "/answers/grief",
  "Identity & Self-Worth": "/answers/identity",
  "Relationships & Communication": "/answers/relationships",
  "Spirituality & Existential": "/answers/spirituality",
  "Teens & Parenting": "/answers/teens",
  "Work & Life Balance": "/answers/work-life",
  "Mindfulness & Meditation": "/answers/mindfulness",
  "Therapy & Treatment": "/answers/therapy",
  "Trauma & Healing": "/answers/trauma",
  "Emotions & Feelings": "/answers/emotions",
  "Sleep & Rest": "/answers/sleep",
  "Addiction & Recovery": "/answers/addiction",
  "Life Transitions": "/answers/life-transitions",
  "Personal Growth": "/answers/personal-growth",
  "Self-Care & Wellness": "/answers/self-care"
};
